buildpack:
  name: Blazar-Buildpack-Java-single-module

# The build environment requires environment variables to be explicitly defined before they may
# be modified by the `write-build-env-var` utilty script to persist changes to an environment variable
# throughout a build
env:
  MAVEN_ARGS: ""
  SET_VERSION: ""
  PKG_RELEASE: ""
  FULL_BUILD_VERSION: ""

before:
  - description: "Prepare build environment"
    commands:
      - $WORKSPACE/build-scripts/prepare_environment.sh
