buildpack:
  name: Blazar-Buildpack-Java-single-module

env:
  HADOOP_DEP_VERSION: "3.3.6-hubspot-SNAPSHOT"

  # Below variables are generated in prepare_environment.sh.
  # The build environment requires environment variables to be explicitly defined before they may
  # be modified by the `write-build-env-var` utilty script to persist changes to an environment variable
  # throughout a build
  SET_VERSION: ""
  HBASE_VERSION: ""
  PKG_RELEASE: ""
  FULL_BUILD_VERSION: ""

before:
  - description: "Prepare build environment"
    commands:
      - $WORKSPACE/build-scripts/prepare_environment.sh

depends:
  - hbase

provides:
  - hbase-client-bundle
  - hbase-mapreduce-bundle
  - hbase-backup-bundle
